//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ApInterfaces
{
    [Serializable]
    public class ButtonMsg : Message
    {
        public const string k_RosMessageName = "ap_interfaces/Button";
        public override string RosMessageName => k_RosMessageName;

        public bool[] kick;

        public ButtonMsg()
        {
            this.kick = new bool[32];
        }

        public ButtonMsg(bool[] kick)
        {
            this.kick = kick;
        }

        public static ButtonMsg Deserialize(MessageDeserializer deserializer) => new ButtonMsg(deserializer);

        private ButtonMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.kick, sizeof(bool), 32);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.kick);
        }

        public override string ToString()
        {
            return "ButtonMsg: " +
            "\nkick: " + System.String.Join(", ", kick.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
