//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ApInterfaces
{
    [Serializable]
    public class TimingMsg : Message
    {
        public const string k_RosMessageName = "ap_interfaces/Timing";
        public override string RosMessageName => k_RosMessageName;

        public long id;
        public double start_loop_ms;
        public double frame_grab_ms;
        public double frame_done_processing_ms;
        public double msg_sent_ms;
        public double msg_received_ms;
        public double begin_render_ms;
        public double end_render_ms;

        public TimingMsg()
        {
            this.id = 0;
            this.start_loop_ms = 0.0;
            this.frame_grab_ms = 0.0;
            this.frame_done_processing_ms = 0.0;
            this.msg_sent_ms = 0.0;
            this.msg_received_ms = 0.0;
            this.begin_render_ms = 0.0;
            this.end_render_ms = 0.0;
        }

        public TimingMsg(long id, double start_loop_ms, double frame_grab_ms, double frame_done_processing_ms, double msg_sent_ms, double msg_received_ms, double begin_render_ms, double end_render_ms)
        {
            this.id = id;
            this.start_loop_ms = start_loop_ms;
            this.frame_grab_ms = frame_grab_ms;
            this.frame_done_processing_ms = frame_done_processing_ms;
            this.msg_sent_ms = msg_sent_ms;
            this.msg_received_ms = msg_received_ms;
            this.begin_render_ms = begin_render_ms;
            this.end_render_ms = end_render_ms;
        }

        public static TimingMsg Deserialize(MessageDeserializer deserializer) => new TimingMsg(deserializer);

        private TimingMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.start_loop_ms);
            deserializer.Read(out this.frame_grab_ms);
            deserializer.Read(out this.frame_done_processing_ms);
            deserializer.Read(out this.msg_sent_ms);
            deserializer.Read(out this.msg_received_ms);
            deserializer.Read(out this.begin_render_ms);
            deserializer.Read(out this.end_render_ms);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.start_loop_ms);
            serializer.Write(this.frame_grab_ms);
            serializer.Write(this.frame_done_processing_ms);
            serializer.Write(this.msg_sent_ms);
            serializer.Write(this.msg_received_ms);
            serializer.Write(this.begin_render_ms);
            serializer.Write(this.end_render_ms);
        }

        public override string ToString()
        {
            return "TimingMsg: " +
            "\nid: " + id.ToString() +
            "\nstart_loop_ms: " + start_loop_ms.ToString() +
            "\nframe_grab_ms: " + frame_grab_ms.ToString() +
            "\nframe_done_processing_ms: " + frame_done_processing_ms.ToString() +
            "\nmsg_sent_ms: " + msg_sent_ms.ToString() +
            "\nmsg_received_ms: " + msg_received_ms.ToString() +
            "\nbegin_render_ms: " + begin_render_ms.ToString() +
            "\nend_render_ms: " + end_render_ms.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
