//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ApInterfaces
{
    [Serializable]
    public class AddThreeIntsResponse : Message
    {
        public const string k_RosMessageName = "ap_interfaces/AddThreeInts";
        public override string RosMessageName => k_RosMessageName;

        public float ballspeed;
        public float ballradius;
        public float goalsize;
        public float friction;
        public float buttonspeed;
        public sbyte capture;
        public sbyte startstop;

        public AddThreeIntsResponse()
        {
            this.ballspeed = 0.0f;
            this.ballradius = 0.0f;
            this.goalsize = 0.0f;
            this.friction = 0.0f;
            this.buttonspeed = 0.0f;
            this.capture = 0;
            this.startstop = 0;
        }

        public AddThreeIntsResponse(float ballspeed, float ballradius, float goalsize, float friction, float buttonspeed, sbyte capture, sbyte startstop)
        {
            this.ballspeed = ballspeed;
            this.ballradius = ballradius;
            this.goalsize = goalsize;
            this.friction = friction;
            this.buttonspeed = buttonspeed;
            this.capture = capture;
            this.startstop = startstop;
        }

        public static AddThreeIntsResponse Deserialize(MessageDeserializer deserializer) => new AddThreeIntsResponse(deserializer);

        private AddThreeIntsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ballspeed);
            deserializer.Read(out this.ballradius);
            deserializer.Read(out this.goalsize);
            deserializer.Read(out this.friction);
            deserializer.Read(out this.buttonspeed);
            deserializer.Read(out this.capture);
            deserializer.Read(out this.startstop);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ballspeed);
            serializer.Write(this.ballradius);
            serializer.Write(this.goalsize);
            serializer.Write(this.friction);
            serializer.Write(this.buttonspeed);
            serializer.Write(this.capture);
            serializer.Write(this.startstop);
        }

        public override string ToString()
        {
            return "AddThreeIntsResponse: " +
            "\nballspeed: " + ballspeed.ToString() +
            "\nballradius: " + ballradius.ToString() +
            "\ngoalsize: " + goalsize.ToString() +
            "\nfriction: " + friction.ToString() +
            "\nbuttonspeed: " + buttonspeed.ToString() +
            "\ncapture: " + capture.ToString() +
            "\nstartstop: " + startstop.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
